export const InitialUrl =
  'http://ec2-18-185-23-116.eu-central-1.compute.amazonaws.com/'

export const LoginUserUrl = 'login'
export const registerUserUrl = 'register'
export const mentorProfileUrl = 'api/teachers/see/header/profile'
export const mentorInstructorGetAllGroupsUrl = 'api/teachers/find/all/group'
export const mentorNotificationsUrl = 'api/teachers/teacher/notifications'
export const mentorGetStudentsUrl = 'api/teachers/rating/group/by/id?groupId='
export const MentorRemoveStudentsUrl = 'api/teachers/remove_student/'
export const MentorGetLessonByGroupIdUrl =
  'api/teachers/get/lessons/by/groupId?groupId='
export const MentorDeleteLessonByIdUrl = 'api/teachers/delete_lesson/'
export const MentorDelteAssignmentByIdUrl = 'api/teachers/delete_assignment/'
export const MentorGetVotedStudentByAssignmentIdUrl =
  'api/teachers/assigment/id/find/student/submission?assigmentId='
export const MentorDeleteAssignmentByIdUrl = 'api/teachers/delete_assignment/'
export const seoAdminGetAllGroupsUrl = 'api/v1/seo/admin/find/all/group'
export const seoAdminProfileUrl = 'api/v1/seo/admin/see/header/profile'
export const staffAdminGetAllGroups = 'api/v1/staff/admin/get_all_groups'
export const staffAdmingetProfile = 'api/v1/staff/admin/see/header/profile'
export const staffAdminfindallteachers = 'api/v1/staff/admin/find/all/teachers'
export const seoAdmingetFindAllManagerUrl = 'api/v1/seo/admin/find/all/manager'
export const managergetProfileUrl = 'api/managers/see/header/profile'
export const managergetCardGroupsUrl = 'api/managers/get_all_groups'
export const managerStudentsUrl = 'api/managers/find/all/students'
export const managerPutStudentsUrl = 'api/managers/get/by/id/student/pay/true'
export const getStudentProfileUrl = 'api/v1/user/see/header/profile'
export const getCousesUrl = 'api/v1/user/find/all/course'
export const getStudentMyGroupUrl = 'api/v1/user/rating/student/in/my/group'
export const getStudentMyprofileUrl = 'api/v1/user/get/user/profile/by'
export const getStudentNotificationUrl = 'api/v1/user/student/notifications'
export const getManagerNotificationUrl = 'api/managers/manager/notifications'
export const managerInstructorMentorUrl = 'api/managers/find/all/teachers'
export const managerStaffAdminUrl = 'api/managers/find/all/staff/admin'
export const getManagerSeoAdminUrl = 'api/managers/find/all/seo/admin'
export const getAllManagerGroupUrl = 'api/managers/find/all/group/name'
export const getSeoAdminProfileUrl = 'api/v1/seo/admin/see/profile'
export const postSeoAdminProfileSavePhotoUrl = 'api/v1/seo/admin/save/photo'
export const getMyprofileStaffAdminUrl = 'api/v1/staff/admin/see/profile'
export const postStaffAdminProfile = 'api/v1/staff/admin/save/photo'
export const studentNotificationManagerUrl =
  'api/v1/user/student/notifications/pay'
export const getStaffAdminNotification =
  'api/v1/staff/admin/staff_admin/notifications'
